# Generated by Django 3.1.6 on 2024-07-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0009_auto_20240716_0258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preconstruction',
            options={'ordering': ['-last_updated']},
        ),
        migrations.RemoveField(
            model_name='preconstruction',
            name='status',
        ),
        migrations.AlterField(
            model_name='preconstruction',
            name='project_type',
            field=models.CharField(choices=[('Condo', 'Condo'), ('Townhome', 'Townhome'), ('Semi-Detached', 'Semi-Detached'), ('Detached', 'Detached'), ('NaN', 'NaN')], default='Condo', max_length=500),
        ),
    ]
