# Generated by Django 3.1.6 on 2024-07-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0011_remove_preconstruction_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preconstruction',
            name='project_address',
        ),
    ]
