# Generated by Django 3.1.6 on 2024-08-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0013_preconstruction_occupancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preconstruction',
            name='occupancy',
            field=models.IntegerField(blank=True, default=2025, null=True),
        ),
    ]
