# Generated by Django 3.1.6 on 2024-08-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0014_auto_20240820_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preconstruction',
            name='baths',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='preconstruction',
            name='beds',
            field=models.FloatField(default=0),
        ),
    ]
